### ISSUE TITLE
sort: Wrong type argument: stringp, 16

### ISSUE THREAD

**Issue by tareefdev** [ryuslash/avandu#3] opened 2019-12-30 11:08 UTC
Hello. I installed the package, added the following to my config:
````
(setq avandu-tt-rss-api-url "http://192.168.1.196/tt-rss/api/"
      avandu-user "myusername"
      avandu-password "mypassorwd")
````
but invoking `avandu-overview` results in `Wrong type argument: stringp, 16` error.

**Comment by ryuslash** [comment] 2020-01-13 01:42
Hey!

Can you give me a bit more information? Just following these instructions I can't reproduce your issue. Could you show me what the response from your tt-rss server is to the API call that Avandu makes?

**Comment by tareefdev** [comment] 2020-01-13 09:58
Maybe there was a need to restart Emacs or something after installing the package. I tried the command `avandu-overview` now and it works flawlessly. Thanks for your great work.

**Comment by r4dian** [comment] 2022-11-03 11:17
Hello, I'm getting something similar with this pubnix server's ttrss instance:

`(setq avandu-tt-rss-api-url "https://ttrss.sdf.org/api/")` and entering my login info manually.

the result is :

```
Contacting host: ttrss.sdf.org:443 [2 times]
sort: Wrong type argument: stringp, 3979
```

Anything I can do to get more helpful info than that ? @ryuslash

**Comment by ryuslash** [comment] 2022-11-04 04:02
Hello! Thanks for reporting it!

Could you start by enabling debug on error by calling `toggle-debug-on-error` and sending me the backtrace that that should show you?

**Comment by r4dian** [comment] 2022-11-04 10:44
```
Debugger entered--Lisp error: (wrong-type-argument stringp 3979)
  avandu--order-feed(((id . 3212276) (guid . "{\"ver\":2,\"uid\":239,\"hash\":\"SHA1:86236d732045275dea...") (unread . t) (marked . :json-false) (published . :json-false) (updated . 1667424949) (is_updated . :json-false) (title . "30 day challenges") (link . "https://austinkleon.com/2022/11/02/30-day-challeng...") (feed_id . 3979) (tags . ["30 day challenge" "miscellany" "newsletter"]) (excerpt . "&hellip;") (labels . []) (feed_title . "Austin Kleon") (comments_count . 0) (comments_link . "") (always_display_attachments . :json-false) (author . "Austin Kleon") (score . 0) (note) (lang . "en")) ((id . 3212517) (guid . "{\"ver\":2,\"uid\":239,\"hash\":\"SHA1:288d9bcde0a727e290...") (unread . t) (marked . :json-false) (published . :json-false) (updated . 1667427339) (is_updated . :json-false) (title . "What Is Wavetable Synthesis?") (link . "https://blog.native-instruments.com/what-is-waveta...") (feed_id . 4038) (tags . ["production" "sound design" "synthesis" "tips and tricks"]) (excerpt . "&hellip;") (labels . []) (feed_title . "Native Instruments Blog") (comments_count . 0) (comments_link . "") (always_display_attachments . :json-false) (author . "Native Instruments") (score . 0) (note) (lang . "en")))
  sort((((id . 3212517) (guid . "{\"ver\":2,\"uid\":239,\"hash\":\"SHA1:288d9bcde0a727e290...") (unread . t) (marked . :json-false) (published . :json-false) (updated . 1667427339) (is_updated . :json-false) (title . "What Is Wavetable Synthesis?") (link . "https://blog.native-instruments.com/what-is-waveta...") (feed_id . 4038) (tags . ["production" "sound design" "synthesis" "tips and tricks"]) (excerpt . "&hellip;") (labels . []) (feed_title . "Native Instruments Blog") (comments_count . 0) (comments_link . "") (always_display_attachments . :json-false) (author . "Native Instruments") (score . 0) (note) (lang . "en"))) avandu--order-feed)
  avandu-overview()
  funcall-interactively(avandu-overview)
  call-interactively(avandu-overview record nil)
  command-execute(avandu-overview record)
  execute-extended-command(nil "avandu-overview" #("avand" 0 5 (ws-butler-chg chg)))
  funcall-interactively(execute-extended-command nil "avandu-overview" #("avand" 0 5 (ws-butler-chg chg)))
  call-interactively(execute-extended-command nil nil)
  command-execute(execute-extended-command)
```

**Comment by ryuslash** [comment] 2022-11-04 17:03
Thanks! I see what the problem is. I'm not sure why this hasn't been a problem before, did the API change at all?

Anyway, I'll try and get a fix for this, hopefully later today :)

**Comment by ryuslash** [comment] 2022-11-06 09:36
@r4dian CL 887efba should fix the issue, hopefully. Unfortunately I don't have access to a Tiny Tiny RSS instance at the moment so I couldn't test it. If it still doesn't work or I've broken it more, please let me know!

**Comment by r4dian** [comment] 2022-11-07 10:14
Works for me. Thanks!

**Closed as completed** 2022-11-08 04:25 UTC
